# Generated by Django 5.0.1 on 2026-07-23 04:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-box",
                        help_text="FontAwesome icon class name e.g. fa-gift",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.00"), "0%"),
                            (Decimal("5.00"), "5%"),
                            (Decimal("12.00"), "12%"),
                            (Decimal("18.00"), "18%"),
                            (Decimal("28.00"), "28%"),
                        ],
                        decimal_places=2,
                        default=Decimal("18.00"),
                        max_digits=5,
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                ("min_stock_level", models.IntegerField(default=5)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("Pcs", "Pieces (Pcs)"),
                            ("Box", "Box"),
                            ("Pkg", "Package"),
                            ("Sheet", "Sheet"),
                            ("Meter", "Meter"),
                            ("Set", "Set"),
                            ("Pack", "Pack"),
                        ],
                        default="Pcs",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
