# Generated by Django 5.0.1 on 2026-07-23 04:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("XEROX", "Xerox & Photocopy"),
                            ("PRINTING", "Color & Black/White Printing"),
                            ("DTP", "DTP & Document Typing"),
                            ("LAMINATION", "Lamination"),
                            ("PHOTO", "Passport & Studio Photos"),
                            ("ONLINE", "Online Forms & Government Work"),
                            ("BINDING", "Spiral & Book Binding"),
                        ],
                        default="XEROX",
                        max_length=30,
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        default="Per Page",
                        help_text="e.g. Per Page, Per Photo, Per Copy",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.00"), max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
