# Generated by Django 5.0.1 on 2026-07-23 14:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("PAPER", "Paper & Sheets"),
                            ("INK", "Ink & Toner Cartridge"),
                            ("OTHER", "Lamination & Binding Supplies"),
                        ],
                        default="PAPER",
                        max_length=20,
                    ),
                ),
                (
                    "brand_or_model",
                    models.CharField(
                        blank=True,
                        help_text="e.g. JK Copier, Canon IR-2520, Epson L3250",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="Rim",
                        help_text="e.g. Rim, Bottle, Cartridge, Pack, Sheets",
                        max_length=50,
                    ),
                ),
                (
                    "min_stock_alert",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.00"), max_digits=10
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("last_refilled_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["item_type", "name"],
            },
        ),
    ]
