# Generated by Django 6.0.7 on 2026-08-01 12:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_rechargeprovider_rechargetransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rechargetransaction",
            name="payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ONLINE", "Online / UPI")],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OtherServiceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("COLLEGE_FORM", "College / Online Form Submission"),
                            ("ELECTRICITY_BILL", "Electricity / Light Bill Payment"),
                            ("CASH_WITHDRAWAL", "Payment Banks Cash Withdrawal / AEPS"),
                            ("MONEY_TRANSFER", "Money Transfer / DMT"),
                        ],
                        default="COLLEGE_FORM",
                        max_length=30,
                    ),
                ),
                (
                    "title_or_biller",
                    models.CharField(
                        help_text="e.g. FY B.Com Admission Form, MSEB Light Bill, Bank Cash Out",
                        max_length=200,
                    ),
                ),
                (
                    "customer_info",
                    models.CharField(
                        help_text="Customer Name, Mobile No, or Consumer ID",
                        max_length=200,
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bill Amount or Cash Withdrawal Amount",
                        max_digits=12,
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Accepted Fee / Editable Commission",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("ONLINE", "Online / UPI")],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
