# Generated by Django 6.0.7 on 2026-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_rechargetransaction_payment_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherservicetransaction",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("ONLINE", "Online / UPI"),
                    ("KHATA", "Customer Khata (Credit)"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rechargetransaction",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("ONLINE", "Online / UPI"),
                    ("KHATA", "Customer Khata (Credit)"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
