# Generated by Django 6.0.7 on 2026-08-04 15:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_otherservicetransaction_payment_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomServiceDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. PAN Card Application, Aadhaar Update, MahaDBT Scholarship",
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COLLEGE_FORM", "College / Online Form Submission"),
                            ("ELECTRICITY_BILL", "Electricity / Light Bill Payment"),
                            ("CASH_WITHDRAWAL", "Payment Banks Cash Withdrawal / AEPS"),
                            ("MONEY_TRANSFER", "Money Transfer / DMT"),
                        ],
                        default="COLLEGE_FORM",
                        max_length=30,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fa-file-signature",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="primary",
                        help_text="primary, success, warning, info, dark",
                        max_length=30,
                    ),
                ),
                (
                    "default_govt_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default Govt/Exam Fee",
                        max_digits=10,
                    ),
                ),
                (
                    "default_service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Default Filing Charge",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
