# Generated by Django 6.0.7 on 2026-08-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_customservicedesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechargetransaction",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Optional: Customer name for Khata book reference",
                max_length=150,
                null=True,
            ),
        ),
    ]
