# Generated by Django 5.0.1 on 2026-07-23 14:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EMITracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Shop Display Fridge, Laptop EMI", max_length=200
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(
                        help_text="e.g. HDFC Bank, Bajaj Finserv, Credit Card",
                        max_length=150,
                    ),
                ),
                (
                    "total_loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("monthly_emi", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "due_day_of_month",
                    models.IntegerField(
                        default=5, help_text="Day of month when EMI is due (1 to 31)"
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "tenure_months",
                    models.IntegerField(
                        default=12, help_text="Total duration in months"
                    ),
                ),
                ("paid_installments", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("PAUSED", "Paused"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "EMI Tracker",
                "verbose_name_plural": "EMI Trackers",
                "ordering": ["status", "due_day_of_month", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-receipt",
                        help_text="FontAwesome icon class e.g. fa-receipt",
                        max_length=50,
                    ),
                ),
                (
                    "color_badge",
                    models.CharField(
                        default="bg-primary",
                        help_text="Bootstrap background badge class",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EMIPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI / GPay / PhonePe"),
                            ("BANK", "Bank Transfer"),
                            ("CARD", "Credit / Debit Card"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="personal_services.emitracker",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI / GPay / PhonePe"),
                            ("BANK", "Bank Transfer"),
                            ("CARD", "Credit / Debit Card"),
                            ("OTHER", "Other"),
                        ],
                        default="UPI",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="personal_services.expensecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
    ]
