# Generated by Django 5.0.1 on 2026-07-23 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(default="SHAMBHU GIFT HOUSE", max_length=150),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Gifts, Toys, Stationeries, Xerox & Printing Center",
                        max_length=200,
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(default="Shambhu Nath", max_length=100),
                ),
                ("phone", models.CharField(default="+91 9876543210", max_length=20)),
                (
                    "email",
                    models.EmailField(
                        default="contact@shambhugifthouse.com", max_length=254
                    ),
                ),
                ("gstin", models.CharField(default="10AAAAA0000A1Z5", max_length=20)),
                (
                    "address",
                    models.TextField(default="Main Road, Market Complex, City Center"),
                ),
                (
                    "receipt_header",
                    models.CharField(
                        default="Thank you for shopping at SHAMBHU GIFT HOUSE!",
                        max_length=255,
                    ),
                ),
                (
                    "receipt_footer",
                    models.CharField(
                        default="Goods once sold can be exchanged within 7 days. No Cash Refund.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("module", models.CharField(max_length=50)),
                ("details", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "System Admin"), ("STAFF", "Billing Staff")],
                        default="STAFF",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
