# Generated by Django 6.0.7 on 2026-07-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="address",
            field=models.TextField(
                default="Dhandarphal Bk, Sangamner, Ahilyanagar, 422603"
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="phone",
            field=models.CharField(default="+91 8975027902", max_length=20),
        ),
    ]
